---
- name: Prepare hosts
  hosts: all:!nixos*
  gather_facts: false
  tasks:
    - name: Install Python for Ansible
      ansible.builtin.raw: |
        if command -v apk; then
          apk add -q --no-cache python3 py3-pip py3-packaging
        elif command -v apt-get; then
          apt-get update -y -qq && apt-get install -y -qq python3 python3-pip python3-packaging
        elif command -v dnf; then
          dnf install -y -q python3 python3-pip python3-packaging
        elif command -v zypper; then
          zypper -q --non-interactive install python3 python3-pip python3-packaging
        else
          echo "No supported package manager found" >&2
          exit 1
        fi
      changed_when: false
    - name: Install azure-ai-inference
      ansible.builtin.pip:
        name: azure-ai-inference
        state: present
        break_system_packages: true
- name: Prepare NixOS hosts
  hosts: nixos*
  gather_facts: false
  tasks:
    - name: Install Python for Ansible on NixOS
      ansible.builtin.raw: |
        if command -v python3 || command -v python; then
          exit 0
        fi
        mkdir -p /etc/nix
        printf "sandbox = false\n" > /etc/nix/nix.conf
        export NIX_CONFIG="sandbox = false"
        nix-env --option sandbox false \
          -iA nixpkgs.python3 nixpkgs.python3Packages.pip
        /root/.nix-profile/bin/pip install --break-system-packages packaging
      changed_when: false
    - name: Install azure-ai-inference on NixOS
      ansible.builtin.pip:
        name: azure-ai-inference
        state: present
        break_system_packages: true
      changed_when: false
